sudo: false
language: node_js
node_js:
 - 14 # use nodejs v14 LTS
cache: npm
branches:
 only:
  - master # build hexo branch only
script:
 - hexo generate # generate static files
deploy:
 provider: pages
 skip-cleanup: true
 github-token: $GH_TOKEN
 keep-history: true
 on:
  branch: master # solve a permission problem
#target_branch: master
local-dir: public
